server:
  port: 8884
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能，利用微服务名称进行路由
          enabled: true
      #允许跨域访问
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origins: '*'
            allowed-headers: '*'
            allowed-methods:
              - OPTIONS
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        #订单路由 (-)表示集合类型
        - id: route-service-order
          #需要转发的地址  lb:使用nacos本地的负载均衡策略
          uri: lb://service-order
          #断言规则 用于路由规则的匹配
          predicates:
            - Path=/service-order/**
            - Method=GET,POST
          #过滤器,对请求和响应进行修改处理
          filters:
            #转发之前去掉第一层路由
            - StripPrefix=1
            #请求重试
            - name: Retry
              args:
                #重试次数
                retries: 3
                #需要重试的错误(5xx)
                series: SERVER_ERROR
                #成功的请求状态码
                statuses: OK
                #需要重试的方法
                methods: GET

        #库存路由
        - id: route-service-stock
          uri: lb://service-stock
          predicates:
            - Path=/service-stock/**
            - Method=GET,POST
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                retries: 3
                series: SERVER_ERROR
                statuses: OK
                methods: GET

        #日志服务
        - id: route-service-log
          uri: lb://service-log
          predicates:
            - Path=/service-log/**
            - Method=GET,POST
          filters:
            - StripPrefix=1



#配置seata的注册中心
seata:
  enabled: true
  application-id: ${spring.application.name}
  #配置事务分组,根据这个获取tc服务的cluster名称
  tx-service-group: default_tx_group
  #配置seata的配置中心
  config:
    type: nacos
    nacos:
      group: DEFAULT_GROUP
      namespace: ''
      username: nacos
      password: nacos
      server-addr: 192.168.181.131:8848
  registry:
    type: nacos
    nacos:
      application: seata-server
      group: DEFAULT_GROUP
      namespace: ''
      username: nacos
      password: nacos
      server-addr: 192.168.181.131:8848
  service:
    #事务组与TC服务cluster的映射关系
    vgroupMapping:
      default_tx_group: default