server:
  port: 8885
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.181.131:3306/test?characterEncoding=utf8&useAffectedRows=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
  cloud:
    sentinel:
      datasource:
        ds:
          nacos:
            server-addr: 192.168.181.131:8848
            data-id: ${spring.application.name}-sentinel
            group-id: DEFAULT_GROUP
            rule-type: flow
      #限流降级数据看板
      transport:
        port: 8719
        dashboard: 192.168.181.131:8858
        eager: true

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  global-config:
    db-config:
      id-type: auto


# 配置openfeign默认超时时间  默认时间 单位毫秒
feign:
  client:
    default-config:
      connectTimeout: 5000
      readTimeout: 10000

#配置seata的注册中心
seata:
  enabled: true
  application-id: ${spring.application.name}
  #配置事务分组,根据这个获取tc服务的cluster名称
  tx-service-group: default_tx_group
  #配置seata的配置中心
  config:
    type: nacos
    nacos:
      group: DEFAULT_GROUP
      namespace: ''
      username: nacos
      password: nacos
      server-addr: 192.168.181.131:8848
  registry:
    type: nacos
    nacos:
      application: seata-server
      group: DEFAULT_GROUP
      namespace: ''
      username: nacos
      password: nacos
      server-addr: 192.168.181.131:8848
  service:
    #事务组与TC服务cluster的映射关系
    vgroupMapping:
      default_tx_group: default
